[".config/kitty/themes/tokyonight_day.conf"]
  type = "file"
  url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/stable/extras/kitty/tokyonight_day.conf"

[".config/kitty/themes/tokyonight_moon.conf"]
  type = "file"
  url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/stable/extras/kitty/tokyonight_moon.conf"

[".config/kitty/themes/tokyonight_night.conf"]
  type = "file"
  url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/stable/extras/kitty/tokyonight_night.conf"

[".config/kitty/themes/tokyonight_storm.conf"]
  type = "file"
  url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/stable/extras/kitty/tokyonight_storm.conf"

[".config/tmux/themes/tokyonight_day.tmux"]
  type = "file"
  url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/stable/extras/tmux/tokyonight_day.tmux"

[".config/tmux/themes/tokyonight_moon.tmux"]
  type = "file"
  url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/stable/extras/tmux/tokyonight_moon.tmux"

[".config/tmux/themes/tokyonight_night.tmux"]
  type = "file"
  url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/stable/extras/tmux/tokyonight_night.tmux"

[".config/tmux/themes/tokyonight_storm.tmux"]
  type = "file"
  url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/stable/extras/tmux/tokyonight_storm.tmux"
